server:
  port: 9001

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      db-name: test
    freemarker:
      enabled: true
      suffix: .ftl
cola:
  devtools: #开发工具
    project-location: D:/test/repository/cola-cloud/cola-cloud-services/cola-cloud-autonumber
    developer: yangy
    table-prefix: t_

constants:
    # QQ
    qqAppId: xxxxxxxx
    qqAppSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    qqRedirectUrl: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #WECAT
    weCatAppId: wxf68782ded2a1a4c2
    weCatAppSecret: 58ed40bd75110f819bdde2216fa28f99
    weCatRedirectUrl: http://localhost:9001/callback.do

